In [14]:
import gym
import numpy as np
import random
import time


In [18]:
env = gym.make("FrozenLake",render_mode="human")

In [16]:
action_space_size=env.action_space.n
state_space_size=env.observation_space.n


q_table=np.zeros((state_space_size,action_space_size))

print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
num_episodes=10000
max_steps_per_episode=100

learning_rate=0.1
discount_rate=0.99

exploration_rate=1
max_exploration_rate=1
min_exploration_rate=0.01
exploration_decay_rate=0.001

In [12]:
rewards_all_episodes=[]

#Q-Learning algorithm

for episode in range(num_episodes):
  state=env.reset()[0]
  done=False
  rewards_current_episode=0

  for step in range (max_steps_per_episode):
    # Exploration-exploitation trade off
    exploration_rate_threshold=random.uniform(0,1)
    if exploration_rate_threshold>exploration_rate:
       action=np.argmax(q_table[state,:])
    else :
       action =env.action_space.sample()

    new_state,reward,done,truncated,info=env.step(action)


    
#Update Q-table for Q(s,a)

    q_table[state,action]=q_table[state,action]*(1-learning_rate)+\
    learning_rate*(reward+discount_rate*np.max(q_table[new_state,:]))

    state=new_state

    rewards_current_episode += reward
    if done == True:
      break


#Exploration rate decay
  
  exploration_rate=min_exploration_rate +\
     (max_exploration_rate-min_exploration_rate)*\
     np.exp(-exploration_decay_rate*episode)
  
  rewards_all_episodes.append(rewards_current_episode)


#Calculate and print the average reward per thousand episodes

rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),\
                                         num_episodes/1000)
count=1000

print("*****Average reward per thousand episodes*****\n")

for r in rewards_per_thousand_episodes:
  print(count," : ",str(sum(r/1000)))
  count+=1000


#print updated Q-table

print("\n\n ******** Q-table***********\n")
print(q_table)

*****Average reward per thousand episodes*****

1000  :  0.03400000000000002
2000  :  0.21400000000000016
3000  :  0.4290000000000003
4000  :  0.5590000000000004
5000  :  0.6520000000000005
6000  :  0.6590000000000005
7000  :  0.6720000000000005
8000  :  0.6680000000000005
9000  :  0.6780000000000005
10000  :  0.6920000000000005


 ******** Q-table***********

[[0.58799275 0.51176071 0.50889236 0.51707248]
 [0.3970355  0.35846067 0.36559446 0.53529729]
 [0.40890404 0.42196224 0.40336408 0.47980876]
 [0.36911404 0.30543768 0.34007224 0.45391466]
 [0.59835968 0.39186241 0.4097385  0.24754623]
 [0.         0.         0.         0.        ]
 [0.20849826 0.08149904 0.32991197 0.20326021]
 [0.         0.         0.         0.        ]
 [0.44230122 0.34149624 0.3289257  0.62457904]
 [0.33828807 0.66074664 0.51476001 0.37352293]
 [0.6635768  0.39234057 0.40245743 0.404595  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.34718703 0.6133203  0.

In [13]:
for episode in range(3):
  state=env.reset()[0]
  done = False
  print("*****Episode " , episode+1 , "*****\n\n\n\n")
  time.sleep(1)
  for step in range (max_steps_per_episode):
    clear_output(wait=True)
    env.render()
    time.sleep(0.3)

    action=np.argmax(q_table[state,:])
    new_state,reward,done,truncated,info=env.step(action)

    if done:
      clear_output(wait=True)
      env.render()
      if reward==1:
        print("****You reached the goal!!*****")
        time.sleep(3).
        
      else:
        print("****You fell through a hole!!****")
        time.sleep(3)
      clear_output(wait=True)
      break
    state=new_state

env.close()

****You reached the goal!!*****
